module.exports = [
  "AAPL","AMZN","DIS","GOOG","INTC","LUV","MRK","MSFT","NFLX","NKE","NVDA","QCOM","SBUX","TSLA","VZ"
];

// "AAPL","AMZN","DIS","GOOG","INTC","LUV","MRK","MSFT","NKE","NFLX","NOK","NVDA","QCOM","SBUX","TSLA","VZ"

// AAPL,AMZN,DIS,GOOG,INTC,LUV,MRK,MSFT,NKE,NFLX,NOK,NVDA,QCOM,SBUX,TSLA,VZ  